import { CheckmarkCircle02Icon, Download04Icon, StarIcon, Wrench01Icon } from '@hugeicons/core-free-icons';
import { HugeiconsIcon } from '@hugeicons/react';
import type { MarketplaceAgent } from '@/types';
import { useTranslation } from 'react-i18next';
import { getToolDisplayLabel } from '@/lib/chat/toolDisplayLabels';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Item, ItemContent, ItemDescription, ItemGroup, ItemMedia, ItemTitle } from '@/components/ui/item';
import { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle } from '@/components/ui/sheet';
import { Spinner } from '@/components/ui/spinner';
interface MarketplaceAgentDetailProps { agent: MarketplaceAgent; isInstalled: boolean; hasUpdate?: boolean; isInstalling: boolean; onInstall: (agent: MarketplaceAgent) => void; onClose: () => void; }
export default function MarketplaceAgentDetail({ agent, isInstalled, hasUpdate = false, isInstalling, onInstall, onClose }: MarketplaceAgentDetailProps) { const { t } = useTranslation(); return <Sheet open onOpenChange={(open) => { if (!open) onClose(); }}><SheetContent className="sm:max-w-lg"><SheetHeader><div className="flex items-start gap-3"><img src={`/agents/sprite_${agent.iconIndex}.png`} alt="" className="size-12 rounded-xl bg-muted object-contain" /><div className="min-w-0"><SheetTitle>{agent.name}</SheetTitle><SheetDescription>by {agent.author} · v{agent.version}</SheetDescription></div></div>{agent.featured ? <Badge className="w-fit"><HugeiconsIcon icon={StarIcon} />Dome Team</Badge> : null}</SheetHeader><div className="flex min-h-0 flex-1 flex-col gap-5 overflow-y-auto px-6 pb-6"><p className="text-sm leading-relaxed">{agent.longDescription ?? agent.description}</p><section className="flex flex-col gap-2"><h3 className="text-xs font-medium text-muted-foreground">{t('marketplace.categories', 'Categories')}</h3><div className="flex flex-wrap gap-2">{agent.tags.map((tag) => <Badge key={tag} variant="secondary">{tag}</Badge>)}</div></section>{agent.toolIds.length ? <section className="flex flex-col gap-2"><h3 className="flex items-center gap-2 text-xs font-medium text-muted-foreground"><HugeiconsIcon icon={Wrench01Icon} />{t('marketplace.tools', 'Tools')}</h3><ItemGroup>{agent.toolIds.map((toolId) => <Item key={toolId} size="xs" variant="outline"><ItemMedia variant="icon"><HugeiconsIcon icon={Wrench01Icon} /></ItemMedia><ItemContent><ItemTitle>{getToolDisplayLabel(toolId, t)}</ItemTitle><ItemDescription>{toolId}</ItemDescription></ItemContent></Item>)}</ItemGroup></section> : null}<section className="flex flex-col gap-2"><h3 className="text-xs font-medium text-muted-foreground">{t('marketplace.system_instructions', 'System instructions')}</h3><pre className="max-h-48 overflow-auto whitespace-pre-wrap rounded-xl bg-muted p-3 text-xs text-muted-foreground">{agent.systemInstructions}</pre></section></div><SheetFooter><Button type="button" variant="outline" onClick={onClose}>{t('common.cancel', 'Cancel')}</Button><Button type="button" disabled={(isInstalled && !hasUpdate) || isInstalling} onClick={() => onInstall(agent)}>{isInstalling ? <Spinner data-icon="inline-start" /> : isInstalled && !hasUpdate ? <HugeiconsIcon icon={CheckmarkCircle02Icon} data-icon="inline-start" /> : <HugeiconsIcon icon={Download04Icon} data-icon="inline-start" />}{isInstalling ? t('marketplace.installing') : isInstalled && !hasUpdate ? t('marketplace.installed') : hasUpdate ? t('marketplace.update') : t('marketplace.install')}</Button></SheetFooter></SheetContent></Sheet>; }
