import type { WorkflowTemplate } from '@/types/canvas';

/** Pre-built Dome Team workflow templates for the marketplace. */
export const WORKFLOW_CATALOG: WorkflowTemplate[] = [
  // ─── ORIGINAL 5 (fixed with systemAgentRole) ───────────────────────────────

  {
    id: 'dome-workflow-research-write',
    name: 'Research & Write',
    description: 'Investiga un tema en la web y redacta un artículo bien estructurado.',
    longDescription:
      'Este workflow conecta un input de texto con un agente investigador y un agente escritor. Primero busca información relevante en la web y luego redacta un artículo completo con citas y estructura académica.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'writing', 'productivity'],
    featured: true,
    downloads: 1247,
    createdAt: 1709251200000,
    estimatedTime: '~2 min',
    difficulty: 'beginner',
    inputTypes: ['text'],
    outputType: 'article',
    category: 'research',
    useCases: [
      'Redactar artículos académicos sobre cualquier tema',
      'Crear posts de blog bien documentados',
      'Preparar informes de investigación de mercado',
    ],
    nodes: [
      {
        id: 'rw-input',
        type: 'textInput',
        position: { x: 80, y: 160 },
        data: { type: 'text-input', label: 'Tema a investigar', value: '' },
      },
      {
        id: 'rw-researcher',
        type: 'agent',
        position: { x: 80, y: 320 },
        data: {
          type: 'agent',
          label: 'Investigador',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'rw-writer',
        type: 'agent',
        position: { x: 80, y: 490 },
        data: {
          type: 'agent',
          label: 'Escritor',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'rw-output',
        type: 'output',
        position: { x: 80, y: 660 },
        data: { type: 'output', label: 'Artículo Final', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'rw-e1', source: 'rw-input', target: 'rw-researcher' },
      { id: 'rw-e2', source: 'rw-researcher', target: 'rw-writer' },
      { id: 'rw-e3', source: 'rw-writer', target: 'rw-output' },
    ],
  },

  {
    id: 'dome-workflow-pdf-summarizer',
    name: 'PDF Summarizer',
    description: 'Resume cualquier documento de tu biblioteca con puntos clave.',
    longDescription:
      'Conecta un documento de tu biblioteca con un agente analista para obtener un resumen ejecutivo con los puntos más importantes, conclusiones y preguntas de reflexión.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'productivity', 'education'],
    featured: true,
    downloads: 2089,
    createdAt: 1709251200000,
    estimatedTime: '~1 min',
    difficulty: 'beginner',
    inputTypes: ['document'],
    outputType: 'summary',
    category: 'research',
    useCases: [
      'Obtener resúmenes ejecutivos de PDFs largos',
      'Extraer conceptos clave de libros o artículos',
      'Preparar notas de lectura rápidas',
    ],
    nodes: [
      {
        id: 'ps-doc',
        type: 'document',
        position: { x: 120, y: 160 },
        data: {
          type: 'document',
          label: 'Documento a resumir',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'ps-analyst',
        type: 'agent',
        position: { x: 120, y: 330 },
        data: {
          type: 'agent',
          label: 'Analista',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ps-output',
        type: 'output',
        position: { x: 120, y: 500 },
        data: { type: 'output', label: 'Resumen', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'ps-e1', source: 'ps-doc', target: 'ps-analyst' },
      { id: 'ps-e2', source: 'ps-analyst', target: 'ps-output' },
    ],
  },

  {
    id: 'dome-workflow-study-guide',
    name: 'Study Guide Creator',
    description: 'Transforma un documento en una guía de estudio con flashcards.',
    longDescription:
      'Ideal para estudiantes. Este workflow toma un documento de tu biblioteca, lo procesa con un agente de biblioteca y genera una guía completa con resúmenes, conceptos clave y flashcards de repaso. Luego un agente escritor da formato final al material.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['education', 'learning'],
    featured: true,
    downloads: 1834,
    createdAt: 1709251200000,
    estimatedTime: '~2 min',
    difficulty: 'beginner',
    inputTypes: ['document', 'text'],
    outputType: 'study_guide',
    category: 'education',
    useCases: [
      'Preparar exámenes universitarios',
      'Crear material de repaso para estudiantes',
      'Generar fichas de estudio desde apuntes',
    ],
    nodes: [
      {
        id: 'sg-doc',
        type: 'document',
        position: { x: 120, y: 120 },
        data: {
          type: 'document',
          label: 'Material de estudio',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'sg-context',
        type: 'textInput',
        position: { x: 440, y: 120 },
        data: {
          type: 'text-input',
          label: 'Contexto (opcional)',
          value: 'Crea una guía de estudio completa con conceptos clave, resumen y preguntas de repaso.',
        },
      },
      {
        id: 'sg-library',
        type: 'agent',
        position: { x: 120, y: 300 },
        data: {
          type: 'agent',
          label: 'Extractor',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'sg-writer',
        type: 'agent',
        position: { x: 280, y: 460 },
        data: {
          type: 'agent',
          label: 'Formateador',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'sg-output',
        type: 'output',
        position: { x: 280, y: 620 },
        data: { type: 'output', label: 'Guía de Estudio', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'sg-e1', source: 'sg-doc', target: 'sg-library' },
      { id: 'sg-e2', source: 'sg-context', target: 'sg-library' },
      { id: 'sg-e3', source: 'sg-library', target: 'sg-writer' },
      { id: 'sg-e4', source: 'sg-writer', target: 'sg-output' },
    ],
  },

  {
    id: 'dome-workflow-content-pipeline',
    name: 'Content Pipeline',
    description: 'Pipeline completo: idea → investigación → redacción → revisión.',
    longDescription:
      'Un pipeline de tres etapas para crear contenido de alta calidad. Parte de una idea en texto, investiga el tema con fuentes web, escribe el contenido y finalmente lo revisa y optimiza antes de la publicación.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['content', 'writing', 'marketing'],
    featured: true,
    downloads: 963,
    createdAt: 1709251200000,
    estimatedTime: '~4 min',
    difficulty: 'intermediate',
    inputTypes: ['text'],
    outputType: 'article',
    category: 'writing',
    useCases: [
      'Crear contenido para redes sociales o blogs',
      'Producir newsletters con investigación incluida',
      'Generar piezas de marketing basadas en datos',
    ],
    nodes: [
      {
        id: 'cp-idea',
        type: 'textInput',
        position: { x: 120, y: 120 },
        data: { type: 'text-input', label: 'Idea/Tema', value: '' },
      },
      {
        id: 'cp-research',
        type: 'agent',
        position: { x: 120, y: 290 },
        data: {
          type: 'agent',
          label: 'Investigador',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'cp-writer',
        type: 'agent',
        position: { x: 120, y: 460 },
        data: {
          type: 'agent',
          label: 'Escritor',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'cp-output',
        type: 'output',
        position: { x: 120, y: 630 },
        data: { type: 'output', label: 'Contenido Final', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'cp-e1', source: 'cp-idea', target: 'cp-research' },
      { id: 'cp-e2', source: 'cp-research', target: 'cp-writer' },
      { id: 'cp-e3', source: 'cp-writer', target: 'cp-output' },
    ],
  },

  {
    id: 'dome-workflow-data-report',
    name: 'Data Report',
    description: 'Analiza un Excel o documento de datos y genera un informe ejecutivo.',
    longDescription:
      'Diseñado para analistas. Conecta un documento de datos o Excel con el agente de datos para obtener insights, estadísticas y tendencias. Luego un agente escritor produce el informe final con recomendaciones accionables.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['data', 'analytics', 'productivity'],
    featured: true,
    downloads: 712,
    createdAt: 1709251200000,
    estimatedTime: '~2 min',
    difficulty: 'intermediate',
    inputTypes: ['document', 'text'],
    outputType: 'report',
    category: 'data',
    useCases: [
      'Generar informes de ventas o KPIs',
      'Analizar resultados de encuestas',
      'Crear reportes automáticos de datos empresariales',
    ],
    nodes: [
      {
        id: 'dr-data',
        type: 'document',
        position: { x: 120, y: 120 },
        data: {
          type: 'document',
          label: 'Datos / Excel',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'dr-instructions',
        type: 'textInput',
        position: { x: 440, y: 120 },
        data: {
          type: 'text-input',
          label: 'Instrucciones',
          value: 'Analiza estos datos y genera un informe ejecutivo con estadísticas clave, tendencias y recomendaciones.',
        },
      },
      {
        id: 'dr-analyst',
        type: 'agent',
        position: { x: 280, y: 300 },
        data: {
          type: 'agent',
          label: 'Data Analyst',
          agentId: null,
          systemAgentRole: 'data',
          agentName: 'Data Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'dr-writer',
        type: 'agent',
        position: { x: 280, y: 470 },
        data: {
          type: 'agent',
          label: 'Redactor',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'dr-output',
        type: 'output',
        position: { x: 280, y: 640 },
        data: { type: 'output', label: 'Informe Ejecutivo', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'dr-e1', source: 'dr-data', target: 'dr-analyst' },
      { id: 'dr-e2', source: 'dr-instructions', target: 'dr-analyst' },
      { id: 'dr-e3', source: 'dr-analyst', target: 'dr-writer' },
      { id: 'dr-e4', source: 'dr-writer', target: 'dr-output' },
    ],
  },

  // ─── 5 TEMPLATES NUEVOS ────────────────────────────────────────────────────

  {
    id: 'dome-workflow-meeting-actions',
    name: 'Meeting Notes → Actions',
    description: 'Convierte notas de reunión en tareas accionables y seguimiento.',
    longDescription:
      'Pega las notas de una reunión y este workflow las procesa con un agente escritor para extraer puntos clave, decisiones tomadas, tareas asignadas con responsables y próximos pasos. Ideal para equipos que quieren maximizar el valor de sus reuniones.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['productivity', 'writing'],
    featured: true,
    downloads: 589,
    createdAt: 1709251200000,
    estimatedTime: '~1 min',
    difficulty: 'beginner',
    inputTypes: ['text'],
    outputType: 'action_list',
    category: 'productivity',
    useCases: [
      'Procesar notas de reuniones de equipo',
      'Extraer tareas y responsables de briefings',
      'Crear actas estructuradas desde notas rápidas',
    ],
    nodes: [
      {
        id: 'ma-notes',
        type: 'textInput',
        position: { x: 120, y: 140 },
        data: {
          type: 'text-input',
          label: 'Notas de la reunión',
          value: '',
        },
      },
      {
        id: 'ma-writer',
        type: 'agent',
        position: { x: 120, y: 310 },
        data: {
          type: 'agent',
          label: 'Procesador',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ma-output',
        type: 'output',
        position: { x: 120, y: 480 },
        data: { type: 'output', label: 'Plan de Acción', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'ma-e1', source: 'ma-notes', target: 'ma-writer' },
      { id: 'ma-e2', source: 'ma-writer', target: 'ma-output' },
    ],
  },

  {
    id: 'dome-workflow-multi-source-synthesis',
    name: 'Multi-Source Synthesis',
    description: 'Sintetiza información de 3 documentos en un análisis comparativo.',
    longDescription:
      'Conecta hasta 3 documentos distintos de tu biblioteca y un agente de biblioteca los analiza en paralelo. Luego un agente escritor crea una síntesis comparativa que identifica similitudes, diferencias y puntos clave de cada fuente.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'education', 'writing'],
    featured: true,
    downloads: 445,
    createdAt: 1709251200000,
    estimatedTime: '~3 min',
    difficulty: 'intermediate',
    inputTypes: ['document'],
    outputType: 'synthesis',
    category: 'research',
    useCases: [
      'Comparar múltiples perspectivas académicas',
      'Revisar literatura de varias fuentes',
      'Analizar competidores o alternativas de producto',
    ],
    nodes: [
      {
        id: 'ms-doc1',
        type: 'document',
        position: { x: 60, y: 120 },
        data: {
          type: 'document',
          label: 'Fuente 1',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'ms-doc2',
        type: 'document',
        position: { x: 280, y: 120 },
        data: {
          type: 'document',
          label: 'Fuente 2',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'ms-doc3',
        type: 'document',
        position: { x: 500, y: 120 },
        data: {
          type: 'document',
          label: 'Fuente 3',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'ms-library',
        type: 'agent',
        position: { x: 280, y: 300 },
        data: {
          type: 'agent',
          label: 'Analizador',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ms-writer',
        type: 'agent',
        position: { x: 280, y: 470 },
        data: {
          type: 'agent',
          label: 'Sintetizador',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ms-output',
        type: 'output',
        position: { x: 280, y: 640 },
        data: { type: 'output', label: 'Síntesis Comparativa', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'ms-e1', source: 'ms-doc1', target: 'ms-library' },
      { id: 'ms-e2', source: 'ms-doc2', target: 'ms-library' },
      { id: 'ms-e3', source: 'ms-doc3', target: 'ms-library' },
      { id: 'ms-e4', source: 'ms-library', target: 'ms-writer' },
      { id: 'ms-e5', source: 'ms-writer', target: 'ms-output' },
    ],
  },

  {
    id: 'dome-workflow-code-reviewer',
    name: 'Code Reviewer',
    description: 'Revisa código con instrucciones personalizadas y genera feedback detallado.',
    longDescription:
      'Conecta un documento con código fuente y agrega instrucciones de revisión. El agente escritor actúa como code reviewer senior y genera un informe de calidad con problemas detectados, mejoras sugeridas, patrones identificados y recomendaciones de refactoring.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['productivity', 'writing'],
    featured: false,
    downloads: 334,
    createdAt: 1709251200000,
    estimatedTime: '~1 min',
    difficulty: 'intermediate',
    inputTypes: ['document', 'text'],
    outputType: 'review',
    category: 'productivity',
    useCases: [
      'Revisar pull requests con contexto específico',
      'Auditar código legado para refactoring',
      'Generar checklists de calidad de código',
    ],
    nodes: [
      {
        id: 'cr-code',
        type: 'document',
        position: { x: 120, y: 120 },
        data: {
          type: 'document',
          label: 'Archivo de código',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'cr-instructions',
        type: 'textInput',
        position: { x: 440, y: 120 },
        data: {
          type: 'text-input',
          label: 'Criterios de revisión',
          value: 'Revisa el código buscando: bugs potenciales, problemas de performance, malas prácticas, falta de manejo de errores y oportunidades de refactoring.',
        },
      },
      {
        id: 'cr-reviewer',
        type: 'agent',
        position: { x: 280, y: 300 },
        data: {
          type: 'agent',
          label: 'Code Reviewer',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'cr-output',
        type: 'output',
        position: { x: 280, y: 480 },
        data: { type: 'output', label: 'Code Review', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'cr-e1', source: 'cr-code', target: 'cr-reviewer' },
      { id: 'cr-e2', source: 'cr-instructions', target: 'cr-reviewer' },
      { id: 'cr-e3', source: 'cr-reviewer', target: 'cr-output' },
    ],
  },

  {
    id: 'dome-workflow-deep-dive',
    name: 'Deep Research Dive',
    description: 'Investigación profunda sobre cualquier tema con fuentes verificadas.',
    longDescription:
      'Usa el poder de la investigación profunda para generar un análisis exhaustivo sobre cualquier tema. El agente investigador realiza múltiples búsquedas, verifica fuentes y produce un informe con secciones estructuradas, citas y referencias. Ideal para trabajos académicos o informes ejecutivos.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'productivity'],
    featured: false,
    downloads: 891,
    createdAt: 1709251200000,
    estimatedTime: '~5 min',
    difficulty: 'advanced',
    inputTypes: ['text'],
    outputType: 'research_report',
    category: 'research',
    useCases: [
      'Investigaciones académicas profundas',
      'Due diligence de mercado o competidores',
      'Análisis de tendencias tecnológicas o sectoriales',
    ],
    nodes: [
      {
        id: 'dd-query',
        type: 'textInput',
        position: { x: 120, y: 140 },
        data: {
          type: 'text-input',
          label: 'Pregunta de investigación',
          value: '',
        },
      },
      {
        id: 'dd-scope',
        type: 'textInput',
        position: { x: 420, y: 140 },
        data: {
          type: 'text-input',
          label: 'Alcance y contexto',
          value: 'Incluye contexto histórico, estado actual, tendencias y perspectivas futuras.',
        },
      },
      {
        id: 'dd-researcher',
        type: 'agent',
        position: { x: 270, y: 310 },
        data: {
          type: 'agent',
          label: 'Deep Researcher',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'dd-writer',
        type: 'agent',
        position: { x: 270, y: 480 },
        data: {
          type: 'agent',
          label: 'Redactor de informe',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'dd-output',
        type: 'output',
        position: { x: 270, y: 650 },
        data: { type: 'output', label: 'Informe de Investigación', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'dd-e1', source: 'dd-query', target: 'dd-researcher' },
      { id: 'dd-e2', source: 'dd-scope', target: 'dd-researcher' },
      { id: 'dd-e3', source: 'dd-researcher', target: 'dd-writer' },
      { id: 'dd-e4', source: 'dd-writer', target: 'dd-output' },
    ],
  },

  {
    id: 'dome-workflow-library-qa',
    name: 'Library Q&A',
    description: 'Responde preguntas usando los documentos de tu biblioteca personal.',
    longDescription:
      'Haz una pregunta y el agente de biblioteca buscará en todos tus documentos para encontrar la respuesta más relevante. Luego el agente escritor presenta la respuesta de forma clara con citas de las fuentes encontradas. Perfecto para recuperar conocimiento almacenado en tu biblioteca.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'education', 'productivity'],
    featured: false,
    downloads: 1102,
    createdAt: 1709251200000,
    estimatedTime: '~1 min',
    difficulty: 'beginner',
    inputTypes: ['text'],
    outputType: 'answer',
    category: 'research',
    useCases: [
      'Consultar documentos y apuntes personales',
      'Recuperar información de PDFs almacenados',
      'Buscar citas o referencias específicas',
    ],
    nodes: [
      {
        id: 'lq-question',
        type: 'textInput',
        position: { x: 120, y: 140 },
        data: {
          type: 'text-input',
          label: 'Tu pregunta',
          value: '',
        },
      },
      {
        id: 'lq-library',
        type: 'agent',
        position: { x: 120, y: 310 },
        data: {
          type: 'agent',
          label: 'Buscador de biblioteca',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'lq-writer',
        type: 'agent',
        position: { x: 120, y: 480 },
        data: {
          type: 'agent',
          label: 'Presentador',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'lq-output',
        type: 'output',
        position: { x: 120, y: 650 },
        data: { type: 'output', label: 'Respuesta', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'lq-e1', source: 'lq-question', target: 'lq-library' },
      { id: 'lq-e2', source: 'lq-library', target: 'lq-writer' },
      { id: 'lq-e3', source: 'lq-writer', target: 'lq-output' },
    ],
  },

  // ─── 5 WORKFLOWS AVANZADOS CON TOOLS REALES ───────────────────────────────

  {
    id: 'dome-workflow-academic-pipeline',
    name: 'Academic Research Pipeline',
    description: 'Pipeline completo: investiga un tema en la web, consulta tu biblioteca y produce un paper académico.',
    longDescription:
      'Pipeline de tres etapas para producción académica rigurosa. El Research Agent busca fuentes web actualizadas y hace deep research. El Library Agent consulta tu biblioteca para integrar conocimiento previo y detectar conexiones. El Writer Agent sintetiza todo en un paper estructurado con citas, marco teórico y conclusiones. El resultado se guarda automáticamente en tu biblioteca.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'writing', 'academic'],
    featured: true,
    downloads: 634,
    createdAt: 1709251200000,
    estimatedTime: '~6 min',
    difficulty: 'advanced',
    inputTypes: ['text'],
    outputType: 'paper',
    category: 'research',
    useCases: [
      'Redactar secciones de tesis o TFG con fuentes verificadas',
      'Producir artículos de revisión de literatura',
      'Crear marcos teóricos bien fundamentados para investigaciones',
    ],
    nodes: [
      {
        id: 'ap-topic',
        type: 'textInput',
        position: { x: 100, y: 120 },
        data: {
          type: 'text-input',
          label: 'Tema de investigación',
          value: '',
        },
      },
      {
        id: 'ap-format',
        type: 'textInput',
        position: { x: 420, y: 120 },
        data: {
          type: 'text-input',
          label: 'Formato y audiencia',
          value: 'Ensayo académico de 1500 palabras en estilo APA. Audiencia: investigadores universitarios. Incluye: introducción con hipótesis, revisión de literatura, desarrollo argumentado, conclusión y bibliografía.',
        },
      },
      {
        id: 'ap-researcher',
        type: 'agent',
        position: { x: 100, y: 300 },
        data: {
          type: 'agent',
          label: 'Investigador Web',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ap-library',
        type: 'agent',
        position: { x: 420, y: 300 },
        data: {
          type: 'agent',
          label: 'Consultor Biblioteca',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ap-writer',
        type: 'agent',
        position: { x: 260, y: 490 },
        data: {
          type: 'agent',
          label: 'Redactor Académico',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ap-output',
        type: 'output',
        position: { x: 260, y: 670 },
        data: { type: 'output', label: 'Paper Académico', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'ap-e1', source: 'ap-topic', target: 'ap-researcher' },
      { id: 'ap-e2', source: 'ap-topic', target: 'ap-library' },
      { id: 'ap-e3', source: 'ap-format', target: 'ap-writer' },
      { id: 'ap-e4', source: 'ap-researcher', target: 'ap-writer' },
      { id: 'ap-e5', source: 'ap-library', target: 'ap-writer' },
      { id: 'ap-e6', source: 'ap-writer', target: 'ap-output' },
    ],
  },

  {
    id: 'dome-workflow-knowledge-graph-builder',
    name: 'Knowledge Graph Builder',
    description: 'Analiza múltiples documentos, extrae conceptos y construye un grafo de conocimiento interconectado.',
    longDescription:
      'Conecta hasta 3 documentos de tu biblioteca y este workflow construye automáticamente una red de conocimiento. El Library Agent extrae conceptos clave y relaciones de cada documento. El Curator Agent crea enlaces semánticos entre recursos, genera el grafo de conocimiento y analiza la estructura resultante para identificar los conceptos centrales y las lagunas temáticas.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'productivity', 'knowledge'],
    featured: true,
    downloads: 289,
    createdAt: 1709251200000,
    estimatedTime: '~3 min',
    difficulty: 'intermediate',
    inputTypes: ['document'],
    outputType: 'knowledge_graph',
    category: 'research',
    useCases: [
      'Construir mapas conceptuales de materiales de investigación',
      'Conectar automáticamente documentos relacionados de una asignatura',
      'Crear una red de conocimiento a partir de un corpus de libros',
    ],
    nodes: [
      {
        id: 'kg-doc1',
        type: 'document',
        position: { x: 60, y: 120 },
        data: {
          type: 'document',
          label: 'Documento 1',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'kg-doc2',
        type: 'document',
        position: { x: 280, y: 120 },
        data: {
          type: 'document',
          label: 'Documento 2',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'kg-doc3',
        type: 'document',
        position: { x: 500, y: 120 },
        data: {
          type: 'document',
          label: 'Documento 3 (opcional)',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'kg-library',
        type: 'agent',
        position: { x: 280, y: 310 },
        data: {
          type: 'agent',
          label: 'Extractor de Conceptos',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'kg-curator',
        type: 'agent',
        position: { x: 280, y: 490 },
        data: {
          type: 'agent',
          label: 'Constructor de Grafo',
          agentId: null,
          systemAgentRole: 'curator',
          agentName: 'Curator Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'kg-output',
        type: 'output',
        position: { x: 280, y: 670 },
        data: { type: 'output', label: 'Grafo de Conocimiento', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'kg-e1', source: 'kg-doc1', target: 'kg-library' },
      { id: 'kg-e2', source: 'kg-doc2', target: 'kg-library' },
      { id: 'kg-e3', source: 'kg-doc3', target: 'kg-library' },
      { id: 'kg-e4', source: 'kg-library', target: 'kg-curator' },
      { id: 'kg-e5', source: 'kg-curator', target: 'kg-output' },
    ],
  },

  {
    id: 'dome-workflow-presentation-builder',
    name: 'Presentation Builder',
    description: 'Investiga un tema y genera automáticamente una presentación PowerPoint con mapa mental.',
    longDescription:
      'Workflow de dos etapas para producir material de presentación de alta calidad. El Research Agent investiga el tema en la web para obtener datos actualizados y relevantes. El Presenter Agent transforma esa investigación en una presentación PowerPoint estructurada y un mapa mental jerárquico que visualiza los conceptos clave. Ambos artefactos se guardan en tu biblioteca.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['content', 'productivity'],
    featured: true,
    downloads: 512,
    createdAt: 1709251200000,
    estimatedTime: '~4 min',
    difficulty: 'intermediate',
    inputTypes: ['text'],
    outputType: 'presentation',
    category: 'productivity',
    useCases: [
      'Crear presentaciones de negocio sobre tendencias del sector',
      'Preparar material docente sobre cualquier tema',
      'Generar decks ejecutivos para reuniones con poco tiempo de preparación',
    ],
    nodes: [
      {
        id: 'pb-topic',
        type: 'textInput',
        position: { x: 100, y: 120 },
        data: {
          type: 'text-input',
          label: 'Tema de la presentación',
          value: '',
        },
      },
      {
        id: 'pb-specs',
        type: 'textInput',
        position: { x: 420, y: 120 },
        data: {
          type: 'text-input',
          label: 'Especificaciones',
          value: 'Presentación de 10-12 diapositivas para audiencia ejecutiva. Incluye: portada, agenda, 6-8 slides de contenido con datos y ejemplos, slide de conclusiones y slide de próximos pasos. También genera un mapa mental resumen.',
        },
      },
      {
        id: 'pb-researcher',
        type: 'agent',
        position: { x: 260, y: 300 },
        data: {
          type: 'agent',
          label: 'Investigador',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'pb-presenter',
        type: 'agent',
        position: { x: 260, y: 480 },
        data: {
          type: 'agent',
          label: 'Diseñador de Presentación',
          agentId: null,
          systemAgentRole: 'presenter',
          agentName: 'Presenter Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'pb-output',
        type: 'output',
        position: { x: 260, y: 660 },
        data: { type: 'output', label: 'Presentación + Mapa Mental', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'pb-e1', source: 'pb-topic', target: 'pb-researcher' },
      { id: 'pb-e2', source: 'pb-specs', target: 'pb-presenter' },
      { id: 'pb-e3', source: 'pb-researcher', target: 'pb-presenter' },
      { id: 'pb-e4', source: 'pb-presenter', target: 'pb-output' },
    ],
  },

  {
    id: 'dome-workflow-study-factory',
    name: 'Study Materials Factory',
    description: 'Transforma un documento en un kit completo de estudio: flashcards, quiz interactivo y mapa mental.',
    longDescription:
      'La fábrica más completa de materiales de estudio. El Library Agent extrae los conceptos clave, definiciones y relaciones del documento fuente. El Presenter Agent genera en paralelo: un deck de flashcards con pregunta-respuesta atómica, un quiz de autoevaluación con preguntas de dificultad progresiva y un mapa mental que visualiza toda la estructura conceptual. Tres artefactos listos para usar directamente en Dome.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['education', 'learning', 'productivity'],
    featured: true,
    downloads: 891,
    createdAt: 1709251200000,
    estimatedTime: '~3 min',
    difficulty: 'beginner',
    inputTypes: ['document', 'text'],
    outputType: 'study_kit',
    category: 'education',
    useCases: [
      'Preparar cualquier examen universitario desde los apuntes',
      'Crear material de repaso para alumnos a partir de un libro',
      'Generar un kit de onboarding de conocimiento para nuevos equipos',
    ],
    nodes: [
      {
        id: 'sf-doc',
        type: 'document',
        position: { x: 120, y: 120 },
        data: {
          type: 'document',
          label: 'Material fuente',
          resourceId: null,
          resourceTitle: null,
          resourceContent: null,
        },
      },
      {
        id: 'sf-focus',
        type: 'textInput',
        position: { x: 440, y: 120 },
        data: {
          type: 'text-input',
          label: 'Foco del estudio',
          value: 'Extrae todos los conceptos clave, definiciones importantes y relaciones entre ideas. Genera: 20 flashcards con pregunta-respuesta atómica, un quiz de 10 preguntas con dificultad progresiva (2 fáciles, 5 medias, 3 difíciles) y un mapa mental con la estructura completa del tema.',
        },
      },
      {
        id: 'sf-library',
        type: 'agent',
        position: { x: 280, y: 310 },
        data: {
          type: 'agent',
          label: 'Extractor de Conocimiento',
          agentId: null,
          systemAgentRole: 'library',
          agentName: 'Library Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'sf-presenter',
        type: 'agent',
        position: { x: 280, y: 490 },
        data: {
          type: 'agent',
          label: 'Generador de Materiales',
          agentId: null,
          systemAgentRole: 'presenter',
          agentName: 'Presenter Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'sf-output',
        type: 'output',
        position: { x: 280, y: 670 },
        data: { type: 'output', label: 'Kit Completo de Estudio', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'sf-e1', source: 'sf-doc', target: 'sf-library' },
      { id: 'sf-e2', source: 'sf-focus', target: 'sf-library' },
      { id: 'sf-e3', source: 'sf-library', target: 'sf-presenter' },
      { id: 'sf-e4', source: 'sf-presenter', target: 'sf-output' },
    ],
  },

  {
    id: 'dome-workflow-competitive-intelligence',
    name: 'Competitive Intelligence',
    description: 'Investiga 3 competidores o temas en paralelo, analiza los datos comparativos y genera un informe estratégico.',
    longDescription:
      'El workflow de inteligencia competitiva más potente. Tres ramas de investigación se ejecutan en paralelo: cada una investiga un competidor, producto o alternativa de forma independiente y profunda. El Data Agent consolida toda la información en una matriz comparativa con métricas clave. El Writer Agent redacta el informe ejecutivo con análisis FODA, posicionamiento relativo y recomendaciones estratégicas.',
    author: 'Dome Team',
    version: '1.0.0',
    tags: ['research', 'data', 'analytics'],
    featured: true,
    downloads: 445,
    createdAt: 1709251200000,
    estimatedTime: '~8 min',
    difficulty: 'advanced',
    inputTypes: ['text'],
    outputType: 'intelligence_report',
    category: 'research',
    useCases: [
      'Analizar competidores antes de lanzar un producto',
      'Comparar tecnologías o frameworks para tomar decisiones de arquitectura',
      'Evaluar alternativas de inversión o proveedores',
    ],
    nodes: [
      {
        id: 'ci-subject1',
        type: 'textInput',
        position: { x: 60, y: 120 },
        data: {
          type: 'text-input',
          label: 'Sujeto A',
          value: '',
        },
      },
      {
        id: 'ci-subject2',
        type: 'textInput',
        position: { x: 280, y: 120 },
        data: {
          type: 'text-input',
          label: 'Sujeto B',
          value: '',
        },
      },
      {
        id: 'ci-subject3',
        type: 'textInput',
        position: { x: 500, y: 120 },
        data: {
          type: 'text-input',
          label: 'Sujeto C',
          value: '',
        },
      },
      {
        id: 'ci-research1',
        type: 'agent',
        position: { x: 60, y: 310 },
        data: {
          type: 'agent',
          label: 'Investigador A',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ci-research2',
        type: 'agent',
        position: { x: 280, y: 310 },
        data: {
          type: 'agent',
          label: 'Investigador B',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ci-research3',
        type: 'agent',
        position: { x: 500, y: 310 },
        data: {
          type: 'agent',
          label: 'Investigador C',
          agentId: null,
          systemAgentRole: 'research',
          agentName: 'Research Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ci-data',
        type: 'agent',
        position: { x: 280, y: 510 },
        data: {
          type: 'agent',
          label: 'Analista Comparativo',
          agentId: null,
          systemAgentRole: 'data',
          agentName: 'Data Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ci-writer',
        type: 'agent',
        position: { x: 280, y: 690 },
        data: {
          type: 'agent',
          label: 'Redactor de Informe',
          agentId: null,
          systemAgentRole: 'writer',
          agentName: 'Writer Agent',
          agentIconIndex: 0,
          status: 'idle',
          outputText: null,
          errorMessage: null,
        },
      },
      {
        id: 'ci-output',
        type: 'output',
        position: { x: 280, y: 870 },
        data: { type: 'output', label: 'Informe de Inteligencia Competitiva', content: null, status: 'idle' },
      },
    ],
    edges: [
      { id: 'ci-e1', source: 'ci-subject1', target: 'ci-research1' },
      { id: 'ci-e2', source: 'ci-subject2', target: 'ci-research2' },
      { id: 'ci-e3', source: 'ci-subject3', target: 'ci-research3' },
      { id: 'ci-e4', source: 'ci-research1', target: 'ci-data' },
      { id: 'ci-e5', source: 'ci-research2', target: 'ci-data' },
      { id: 'ci-e6', source: 'ci-research3', target: 'ci-data' },
      { id: 'ci-e7', source: 'ci-data', target: 'ci-writer' },
      { id: 'ci-e8', source: 'ci-writer', target: 'ci-output' },
    ],
  },
];

export const WORKFLOW_TAGS = [
  'all',
  'research',
  'writing',
  'education',
  'content',
  'data',
  'productivity',
  'marketing',
  'analytics',
  'learning',
  'academic',
  'knowledge',
] as const;

export type WorkflowTag = (typeof WORKFLOW_TAGS)[number];

export const WORKFLOW_CATEGORIES = [
  'all',
  'research',
  'writing',
  'education',
  'data',
  'productivity',
  'knowledge',
] as const;

export type WorkflowCategory = (typeof WORKFLOW_CATEGORIES)[number];
