import { ArrowLeft02Icon, Search01Icon } from '@hugeicons/core-free-icons';
import { HugeiconsIcon } from '@hugeicons/react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { InputGroup, InputGroupAddon, InputGroupInput } from '@/components/ui/input-group';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import type { DataTableData, StudioOutput } from '@/types';
import LearnViewerEmpty from '../LearnViewerEmpty';
interface TableViewProps { output: StudioOutput; onBack: () => void; }
export default function TableView({ output, onBack }: TableViewProps) { const { t } = useTranslation(); const [query, setQuery] = useState(''); const [sortKey, setSortKey] = useState<string | null>(null); const [sortAsc, setSortAsc] = useState(true); const { data, corrupt } = useMemo(() => { if (!output.content) return { data: { columns: [], rows: [] } as DataTableData, corrupt: false }; try { return { data: JSON.parse(output.content) as DataTableData, corrupt: false }; } catch { return { data: { columns: [], rows: [] } as DataTableData, corrupt: true }; } }, [output.content]); const rows = useMemo(() => { let list = [...data.rows]; const q = query.trim().toLowerCase(); if (q) list = list.filter((row) => Object.values(row).some((value) => String(value).toLowerCase().includes(q))); if (sortKey) list.sort((a, b) => (sortAsc ? 1 : -1) * String(a[sortKey] ?? '').localeCompare(String(b[sortKey] ?? ''), undefined, { numeric: true })); return list; }, [data.rows, query, sortKey, sortAsc]); const toggleSort = (key: string) => { if (sortKey === key) setSortAsc((value) => !value); else { setSortKey(key); setSortAsc(true); } }; if (!data.columns.length || !data.rows.length) return <LearnViewerEmpty onBack={onBack} corrupt={corrupt} />; return <div className="flex h-full flex-col gap-4 overflow-y-auto p-5"><Button type="button" variant="ghost" size="sm" className="w-fit" onClick={onBack}><HugeiconsIcon icon={ArrowLeft02Icon} data-icon="inline-start" />{t('learn.back_to_library', 'Back to library')}</Button><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="font-heading text-xl font-semibold">{output.title}</h1><InputGroup className="w-full sm:w-64"><InputGroupAddon><HugeiconsIcon icon={Search01Icon} /></InputGroupAddon><InputGroupInput type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('learn.table_search', 'Search table…')} /></InputGroup></div><div className="overflow-hidden rounded-2xl border"><Table><TableHeader><TableRow>{data.columns.map((column) => <TableHead key={column.key}><Button type="button" variant="ghost" size="sm" onClick={() => toggleSort(column.key)}>{column.label}</Button></TableHead>)}</TableRow></TableHeader><TableBody>{rows.map((row, rowIndex) => <TableRow key={rowIndex}>{data.columns.map((column) => <TableCell key={column.key}>{row[column.key] ?? '—'}</TableCell>)}</TableRow>)}</TableBody></Table></div></div>; }
