import { render, screen, fireEvent } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import type { PlanDocument } from '@/lib/many/planDocument';
import { ManyPlanArtifactSlot, ManyPlanPanel } from './ManyPlanCard';

const { state } = vi.hoisted(() => ({ state: {
  currentSessionId: 'session',
  agentModeBySession: { session: 'agent' },
  planDocumentBySession: {} as Record<string, PlanDocument>,
  planTodosBySession: {} as Record<string, PlanDocument['todos']>,
  planPanelOpenBySession: { session: false },
  setPlanDocumentForSession: vi.fn(),
  setPlanPanelOpenForSession: vi.fn(),
  setAgentModeForSession: vi.fn(),
  setPlanExecutingForSession: vi.fn(),
  setPlanChoiceOpenForSession: vi.fn(),
} }));
vi.mock('@/lib/store/useManyStore', () => ({ useManyStore: Object.assign((selector: (value: typeof state) => unknown) => selector(state), { getState: () => state }) }));
vi.mock('@/components/markdown/MarkdownNoteEditor', () => ({ default: () => null }));
vi.mock('@/components/chat/MermaidDiagram', () => ({ default: () => null }));
vi.mock('@/lib/many/manySendController', () => ({ sendManyUserMessage: vi.fn() }));

const body = 'Plan:\n1. Buscar fuentes\n2. Analizar evidencias';
const document: PlanDocument = { title: 'Investigar', body, excerpt: 'Revisar fuentes', todos: [
  { step: 1, text: 'Buscar fuentes', completed: false },
  { step: 2, text: 'Analizar evidencias', completed: false },
] };

beforeEach(() => {
  state.agentModeBySession.session = 'agent';
  state.planDocumentBySession = {};
  state.planTodosBySession = {};
  state.planPanelOpenBySession.session = false;
});

describe('explicit Plan artifact', () => {
  it('does not turn an Agent list or plan offer into a card', () => {
    render(<ManyPlanArtifactSlot messageId="answer" content={`${body}\n¿Apruebas el plan?`} />);
    expect(screen.queryByRole('button')).toBeNull();
  });

  it('hides legacy inferred plans in Agent and Draft', () => {
    state.planDocumentBySession.session = document;
    const { rerender } = render(<ManyPlanArtifactSlot messageId="answer" content={body} />);
    expect(screen.queryByRole('button')).toBeNull();
    state.agentModeBySession.session = 'draft';
    rerender(<ManyPlanArtifactSlot messageId="answer" content={body} />);
    expect(screen.queryByRole('button')).toBeNull();
  });

  it('opens a plan generated by an explicit Plan run', () => {
    state.planDocumentBySession.session = { ...document, originMode: 'plan' };
    render(<ManyPlanArtifactSlot messageId="answer" content={body} />);
    fireEvent.click(screen.getByRole('button'));
    expect(state.setPlanPanelOpenForSession).toHaveBeenCalledWith('session', true);
  });

  it('does not attach the saved plan to unrelated later answers', () => {
    state.planDocumentBySession.session = { ...document, originMode: 'plan' };
    render(<ManyPlanArtifactSlot messageId="later" content="Estas son las conclusiones." />);
    expect(screen.queryByRole('button')).toBeNull();
  });

  it('does not recover a plan panel from an ordinary answer', () => {
    state.planPanelOpenBySession.session = true;
    const { container } = render(<ManyPlanPanel />);
    expect(container).toBeEmptyDOMElement();
  });
});
