#!/usr/bin/env node
/**
 * Embeds build-time environment variables into electron/app-credentials.cjs
 * Run this before electron-builder in CI to bake credentials into the binary.
 *
 * Usage: node scripts/embed-env.cjs
 * Env vars read: DOME_GOOGLE_DRIVE_CLIENT_ID, DOME_GOOGLE_DRIVE_CLIENT_SECRET,
 *               DOME_PROVIDER_URL (optional; empty → runtime uses packaged https://provider.dome.app),
 *               DOME_GITHUB_CLIENT_ID (GitHub OAuth App client id for project sync; public, safe to bake)
 */

const fs = require('fs');
const path = require('path');

const credentials = {
  DOME_GOOGLE_DRIVE_CLIENT_ID: process.env.DOME_GOOGLE_DRIVE_CLIENT_ID || '',
  DOME_GOOGLE_DRIVE_CLIENT_SECRET: process.env.DOME_GOOGLE_DRIVE_CLIENT_SECRET || '',
  DOME_PROVIDER_URL: (process.env.DOME_PROVIDER_URL || '').trim(),
  DOME_GITHUB_CLIENT_ID: process.env.DOME_GITHUB_CLIENT_ID || '',
};

const content = `// AUTO-GENERATED by scripts/embed-env.cjs — do not edit manually
// Add electron/app-credentials.cjs to .gitignore
module.exports = ${JSON.stringify(credentials, null, 2)};
`;

const outPath = path.join(__dirname, '../electron/app-credentials.cjs');
fs.writeFileSync(outPath, content, 'utf-8');
console.log('[embed-env] Written:', outPath);
for (const [k, v] of Object.entries(credentials)) {
  const label =
    k === 'DOME_GOOGLE_DRIVE_CLIENT_ID' ||
    k === 'DOME_GOOGLE_DRIVE_CLIENT_SECRET' ||
    (k === 'DOME_PROVIDER_URL' && v)
      ? '***set***'
      : k === 'DOME_PROVIDER_URL'
        ? '(empty)'
        : v
          ? '***set***'
          : '(empty)';
  console.log(`[embed-env]   ${k}: ${label}`);
}
