#!/usr/bin/env node
/**
 * Embeds build-time environment variables into electron/app-credentials.cjs
 * Run this before electron-builder in CI to bake credentials into the binary.
 *
 * Usage: node scripts/embed-env.cjs
 * Env vars read: DOME_GOOGLE_DRIVE_CLIENT_ID, DOME_GOOGLE_DRIVE_CLIENT_SECRET
 */

const fs = require('fs');
const path = require('path');

const credentials = {
  DOME_GOOGLE_DRIVE_CLIENT_ID: process.env.DOME_GOOGLE_DRIVE_CLIENT_ID || '',
  DOME_GOOGLE_DRIVE_CLIENT_SECRET: process.env.DOME_GOOGLE_DRIVE_CLIENT_SECRET || '',
};

const content = `// AUTO-GENERATED by scripts/embed-env.cjs — do not edit manually
// Add electron/app-credentials.cjs to .gitignore
module.exports = ${JSON.stringify(credentials, null, 2)};
`;

const outPath = path.join(__dirname, '../electron/app-credentials.cjs');
fs.writeFileSync(outPath, content, 'utf-8');
console.log('[embed-env] Written:', outPath);
for (const [k, v] of Object.entries(credentials)) {
  console.log(`[embed-env]   ${k}: ${v ? '***set***' : '(empty)'}`);
}
