import { ArrowLeft02Icon, Search01Icon } from '@hugeicons/core-free-icons';
import { HugeiconsIcon } from '@hugeicons/react';
import { useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';
import { Button } from '@/components/ui/button';
import { Empty, EmptyHeader, EmptyTitle } from '@/components/ui/empty';
import { InputGroup, InputGroupAddon, InputGroupInput } from '@/components/ui/input-group';
import type { FAQData, StudioOutput } from '@/types';
import LearnViewerEmpty from '../LearnViewerEmpty';
interface FaqReaderProps { output: StudioOutput; onBack: () => void; }
export default function FaqReader({ output, onBack }: FaqReaderProps) { const { t } = useTranslation(); const [query, setQuery] = useState(''); const { data, corrupt } = useMemo(() => { if (!output.content) return { data: { pairs: [] } as FAQData, corrupt: false }; try { return { data: JSON.parse(output.content) as FAQData, corrupt: false }; } catch { return { data: { pairs: [] } as FAQData, corrupt: true }; } }, [output.content]); const filtered = useMemo(() => { const q = query.trim().toLowerCase(); return q ? data.pairs.filter((pair) => pair.question.toLowerCase().includes(q) || pair.answer.toLowerCase().includes(q)) : data.pairs; }, [data.pairs, query]); if (!data.pairs?.length) return <LearnViewerEmpty onBack={onBack} corrupt={corrupt} />; return <div className="mx-auto flex h-full w-full max-w-4xl flex-col gap-5 overflow-y-auto p-5"><Button type="button" variant="ghost" size="sm" className="w-fit" onClick={onBack}><HugeiconsIcon icon={ArrowLeft02Icon} data-icon="inline-start" />{t('learn.back_to_library', 'Back to library')}</Button><div className="flex flex-wrap items-center justify-between gap-3"><h1 className="font-heading text-xl font-semibold">{output.title}</h1><InputGroup className="w-full sm:w-64"><InputGroupAddon><HugeiconsIcon icon={Search01Icon} /></InputGroupAddon><InputGroupInput type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={t('learn.faq_search', 'Search FAQ…')} /></InputGroup></div>{filtered.length === 0 ? <Empty><EmptyHeader><EmptyTitle>{t('learn.faq_empty', 'No matching questions.')}</EmptyTitle></EmptyHeader></Empty> : <Accordion defaultValue={["faq-0"]} multiple>{filtered.map((pair, index) => <AccordionItem key={`${pair.question}-${index}`} value={`faq-${index}`}><AccordionTrigger>{pair.question}</AccordionTrigger><AccordionContent><p className="text-sm leading-relaxed text-muted-foreground">{pair.answer}</p></AccordionContent></AccordionItem>)}</Accordion>}</div>; }
