import { SparklesIcon } from '@hugeicons/core-free-icons';
import { HugeiconsIcon } from '@hugeicons/react';
import { useTranslation } from 'react-i18next';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Item, ItemContent, ItemDescription, ItemGroup, ItemTitle } from '@/components/ui/item';
import { Spinner } from '@/components/ui/spinner';
import type { GenerateProgress, GenerateProgressPhase } from '@/lib/learn/types';
const STEPS: { phase: GenerateProgressPhase; labelKey: string; fallback: string }[] = [{ phase: 'reading', labelKey: 'learn.gen_reading', fallback: 'Reading sources' }, { phase: 'extracting', labelKey: 'learn.gen_extracting', fallback: 'Extracting concepts' }, { phase: 'writing', labelKey: 'learn.gen_writing', fallback: 'Writing draft' }, { phase: 'explaining', labelKey: 'learn.gen_explaining', fallback: 'Adding explanations' }, { phase: 'saving', labelKey: 'learn.gen_saving', fallback: 'Saving' }];
function stepState(stepPhase: GenerateProgressPhase, current?: GenerateProgress | null): 'done' | 'running' | 'pending' { if (!current) return 'pending'; if (current.phase === 'error') return stepPhase === 'reading' ? 'running' : 'pending'; if (current.phase === 'done') return 'done'; const order = STEPS.map((step) => step.phase); const currentIndex = order.indexOf(current.phase); const stepIndex = order.indexOf(stepPhase); return stepIndex < currentIndex ? 'done' : stepIndex === currentIndex ? 'running' : 'pending'; }
interface GenerateProgressViewProps { progress: GenerateProgress | null; onRetry?: () => void; }
export default function GenerateProgressView({ progress, onRetry }: GenerateProgressViewProps) { const { t } = useTranslation(); if (progress?.phase === 'error') return <Alert variant="destructive"><HugeiconsIcon icon={SparklesIcon} /><AlertTitle>{t('learn.generation_failed', 'Generation failed')}</AlertTitle><AlertDescription className="flex flex-col gap-3"><p>{progress.error ?? progress.message}</p>{onRetry ? <Button type="button" variant="outline" className="w-fit" onClick={onRetry}>{t('learn.retry', 'Try again')}</Button> : null}</AlertDescription></Alert>; return <ItemGroup>{STEPS.map((step) => { const state = stepState(step.phase, progress); return <Item key={step.phase} variant={state === 'running' ? 'muted' : 'default'}><ItemContent><ItemTitle>{state === 'running' ? <Spinner data-icon="inline-start" /> : null}{t(step.labelKey, step.fallback)}</ItemTitle>{state === 'running' && progress?.draftItem ? <ItemDescription>{progress.draftItem}</ItemDescription> : null}</ItemContent><Badge variant={state === 'done' ? 'secondary' : 'outline'}>{state}</Badge></Item>; })}</ItemGroup>; }
