import { BookOpen01Icon, BrainIcon, BubbleChatQuestionIcon, CalendarRangeIcon, HeadphonesIcon, HelpCircleIcon, MapsIcon, TableIcon } from '@hugeicons/core-free-icons';
import { HugeiconsIcon, type IconSvgElement } from '@hugeicons/react';
import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { Badge } from '@/components/ui/badge';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import type { StudioOutputType } from '@/types';
interface StepTypePickerProps { selected: StudioOutputType | null; onSelect: (type: StudioOutputType) => void; }
export default function StepTypePicker({ selected, onSelect }: StepTypePickerProps) { const { t } = useTranslation(); const types = useMemo(() => [{ type: 'mindmap' as const, icon: MapsIcon, name: t('learn.type_mindmap', 'Mind map'), sub: t('learn.type_mindmap_desc', 'Concept map') }, { type: 'flashcards' as const, icon: BrainIcon, name: t('learn.tab_decks', 'Flashcards'), sub: t('learn.type_flashcards_desc', 'Spaced repetition') }, { type: 'quiz' as const, icon: HelpCircleIcon, name: t('learn.tab_quizzes', 'Quizzes'), sub: t('learn.type_quiz_desc', 'Multiple choice') }, { type: 'guide' as const, icon: BookOpen01Icon, name: t('learn.tab_guides', 'Guides'), sub: t('learn.type_guide_desc', 'Structured guide') }, { type: 'faq' as const, icon: BubbleChatQuestionIcon, name: t('learn.tab_faqs', 'FAQs'), sub: t('learn.type_faq_desc', 'Questions and answers') }, { type: 'timeline' as const, icon: CalendarRangeIcon, name: t('learn.tab_timelines', 'Timelines'), sub: t('learn.type_timeline_desc', 'Chronological events') }, { type: 'table' as const, icon: TableIcon, name: t('learn.tab_tables', 'Tables'), sub: t('learn.type_table_desc', 'Structured data') }, { type: 'audio' as const, icon: HeadphonesIcon, name: t('learn.type_audio', 'Audio'), sub: t('learn.type_audio_desc', 'Audio summary'), disabled: true }], [t]); return <ToggleGroup value={selected ? [selected] : []} onValueChange={(value) => value[0] && onSelect(value[0] as StudioOutputType)} variant="outline" className="grid w-full grid-cols-1 sm:grid-cols-2">{types.map((entry) => <ToggleGroupItem key={entry.type} value={entry.type} disabled={'disabled' in entry && entry.disabled} className="h-auto min-h-20 justify-start gap-3 p-4 text-left"><HugeiconsIcon icon={entry.icon as IconSvgElement} /><span className="flex min-w-0 flex-1 flex-col items-start"><span className="font-medium">{entry.name}</span><span className="text-xs text-muted-foreground">{entry.sub}</span></span>{'disabled' in entry && entry.disabled ? <Badge variant="secondary">{t('common.coming_soon', 'Soon')}</Badge> : null}</ToggleGroupItem>)}</ToggleGroup>; }
