import { useTranslation } from 'react-i18next';
import { Field, FieldDescription, FieldGroup, FieldLabel } from '@/components/ui/field';
import { Input } from '@/components/ui/input';
import { Slider } from '@/components/ui/slider';
import { Textarea } from '@/components/ui/textarea';
import { ToggleGroup, ToggleGroupItem } from '@/components/ui/toggle-group';
import type { GenerateConfig, GenerateDifficulty, GenerateLanguage } from '@/lib/learn/types';
interface StepConfigureProps { config: GenerateConfig; onChange: (patch: Partial<GenerateConfig>) => void; }
const DIFFICULTIES: { id: GenerateDifficulty; labelKey: string; fallback: string }[] = [{ id: 'easy', labelKey: 'learn.diff_easy', fallback: 'Easy' }, { id: 'mixed', labelKey: 'learn.diff_mixed', fallback: 'Mixed' }, { id: 'hard', labelKey: 'learn.diff_hard', fallback: 'Hard' }, { id: 'exam', labelKey: 'learn.diff_exam', fallback: 'Exam' }];
const LANGUAGES: { id: GenerateLanguage; labelKey: string; fallback: string }[] = [{ id: 'auto', labelKey: 'learn.lang_auto', fallback: 'Auto' }, { id: 'en', labelKey: 'learn.lang_en', fallback: 'English' }, { id: 'es', labelKey: 'learn.lang_es', fallback: 'Spanish' }, { id: 'fr', labelKey: 'learn.lang_fr', fallback: 'French' }];
export default function StepConfigure({ config, onChange }: StepConfigureProps) { const { t } = useTranslation(); return <FieldGroup><Field><FieldLabel htmlFor="learn-gen-title">{t('learn.config_title', 'Title')}</FieldLabel><Input id="learn-gen-title" value={config.title} onChange={(event) => onChange({ title: event.target.value })} placeholder={t('learn.config_title_ph', 'Optional custom title')} /></Field><Field><FieldLabel>{t('learn.config_count', 'Item count')}</FieldLabel><Slider min={5} max={50} step={1} value={[config.count]} onValueChange={(value) => onChange({ count: Array.isArray(value) ? value[0] : value })} aria-label={t('learn.config_count', 'Item count')} /><FieldDescription>{config.count}</FieldDescription></Field><Field><FieldLabel>{t('learn.config_difficulty', 'Difficulty')}</FieldLabel><ToggleGroup value={[config.difficulty]} onValueChange={(value) => value[0] && onChange({ difficulty: value[0] as GenerateDifficulty })} variant="outline">{DIFFICULTIES.map((option) => <ToggleGroupItem key={option.id} value={option.id}>{t(option.labelKey, option.fallback)}</ToggleGroupItem>)}</ToggleGroup></Field><Field><FieldLabel>{t('learn.config_language', 'Language')}</FieldLabel><ToggleGroup value={[config.language]} onValueChange={(value) => value[0] && onChange({ language: value[0] as GenerateLanguage })} variant="outline">{LANGUAGES.map((option) => <ToggleGroupItem key={option.id} value={option.id}>{t(option.labelKey, option.fallback)}</ToggleGroupItem>)}</ToggleGroup></Field><Field><FieldLabel htmlFor="learn-gen-instructions">{t('learn.config_instructions', 'Instructions')}</FieldLabel><Textarea id="learn-gen-instructions" value={config.instructions} onChange={(event) => onChange({ instructions: event.target.value })} placeholder={t('learn.config_instructions_ph', 'Focus areas, tone, or constraints…')} /></Field></FieldGroup>; }
